cache:
  pipeline: ["~/.m2"]

shared:
  annotations:
    screwdriver.cd/cpu: TURBO
    screwdriver.cd/ram: TURBO
  image: maven-non-root:3.5.4-jdk-8-alpine
  environment:
    #Fetches history so Sonar can assign blame.
    GIT_SHALLOW_CLONE: false

jobs:
  pull-request:
    requires: [~pr]
    secrets:
      - COVERALLS_REPO_TOKEN
    steps:
      - install: sudo apt-get install postgresql
      - build: mvn -B clean install

  main:
    secrets:
      - GPG_KEYNAME
      - GPG_PASSPHRASE
      - GPG_ENCPHRASE
      - OSSRH_USER
      - OSSRH_TOKEN
    requires: [~tag, ~release, ~commit]
    steps:
      - install: sudo apt-get install postgresql
      - prepare: "screwdriver/release_prepare.sh"
      - build: mvn -B clean install
      - publish: "screwdriver/publish_to_maven.sh"