cache:
  pipeline: ["~/.m2"]

shared:
  annotations:
    screwdriver.cd/cpu: TURBO
    screwdriver.cd/ram: TURBO
  image: maven:3.6.3-jdk-8
  environment:
    #Fetches history so Sonar can assign blame.
    GIT_SHALLOW_CLONE: false

jobs:
  pull-request:
    requires: [~pr]
    secrets:
      - COVERALLS_REPO_TOKEN
    steps:
      - build: mvn -B clean install

  main:
    secrets:
      - GPG_KEYNAME
      - GPG_PASSPHRASE
      - GPG_ENCPHRASE
      - OSSRH_USER
      - OSSRH_TOKEN
    requires: [~tag, ~release, ~commit]
    steps:
      - createUser: |
          adduser --disabled-password --gecos "" ciuser
          CIUSER_BUILD_DIR=/home/ciuser/build
          cp -r $SHIPPABLE_BUILD_DIR $CIUSER_BUILD_DIR
          chown -R ciuser:ciuser $CIUSER_BUILD_DIR
          su -c "cd $CIUSER_BUILD_DIR" ciuser
      - install: sudo apt-get install postgresql
      - install_libpq: sudo apt-get install libpq-dev
      - prepare: "screwdriver/release_prepare.sh"
      - build: mvn -B clean install
      - publish: "screwdriver/publish_to_maven.sh"
